name: Robot Tests with Allure and Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install webdriver-manager

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Đảm bảo package-lock.json có trong repository

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '137.0.7151.68'

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          python -m webdriver_manager.chrome --driver-version=$CHROME_VERSION

      - name: Run Robot Framework tests
        run: |
          xvfb-run robot --listener allure_robotframework:output/allure-results --outputdir output --variable BROWSER:chrome --variable BROWSER_OPTIONS:"--headless=new;--no-sandbox;--disable-dev-shm-usage" testcase/
        continue-on-error: false

      - name: Generate Allure Report
        run: allure generate output/allure-results -o output/allure --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/allure

      - name: Upload test logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: output/